networks:
   elias_network:
      name: elias_network
      driver: bridge

volumes:
   elias_volume_system:
      external: true
   # elias_volume_mq_data:
   #    external: true
   # elias_volume_mq_log:
   #    external: true

services:
   elias_qs_mysql_db:
      image: mysql:8.4.0-oraclelinux8
      container_name: elias_qs_mysql_db
      hostname: elias_qs_mysql_db
      restart: always
      environment:
         - MYSQL_TCP_PORT=3306
         - MYSQL_ROOT_PASSWORD=1234qQ1!
      ports:
         - 43306:3306
      volumes:
         - elias_volume_system:/var/lib/mysql
      networks:
         - elias_network

   elias_cache_redis:
      image: redis:latest
      container_name: elias_cache_redis
      hostname: elias_cache_redis
      restart: always
      ports:
         - 6379:6379
      networks:
         - elias_network

   elias_message_queue_rabbit_mq:
      image: rabbitmq:management
      container_name: elias_message_queue_rabbit_mq
      hostname: elias_message_queue_rabbit_mq
      restart: always
      environment:
         RABBITMQ_DEFAULT_USER: guest
         RABBITMQ_DEFAULT_PASS: guest
      # volumes:
      #    - elias_volume_mq_data:/var/lib/rabbitmq
      #    - elias_volume_mq_log:/val/log/rabbitmq
      ports:
         - 5672:5672
      networks:
         - elias_network



   # Define the installed services.
   elias_query_service:
      image: miroslavbonchevbonchev/elias_query_service:latest
      container_name: elias_query_service
      hostname: elias_query_service
      restart: always
      volumes:
         - elias_volume_system:/home/app/query
      ports:
         - 8080
      depends_on:
         - elias_qs_mysql_db
         - elias_cache_redis
         - elias_message_queue_rabbit_mq
      networks:
         - elias_network
      environment:
         ASPNETCORE_HTTP_PORTS: 8080

   elias_societal_service:
      image: miroslavbonchevbonchev/elias_societal_service:latest
      container_name: elias_societal_service
      hostname: elias_societal_service
      restart: always
      volumes:
         - elias_volume_system:/home/app/societal
      ports:
         - 8080
      depends_on:
         - elias_query_service
      networks:
         - elias_network
      environment:
         ASPNETCORE_HTTP_PORTS: 8080

   elias_gateway:
      image: miroslavbonchevbonchev/elias_gateway:latest
      container_name: elias_gateway
      hostname: elias_gateway
      restart: always
      volumes:
         - elias_volume_system:/home/app/gateway
      ports:
         - 80:80
         - 443:443
      depends_on:
         - elias_query_service
         - elias_societal_service
#         - elias_web_service
      networks:
         - elias_network
      environment:
         ASPNETCORE_HTTP_PORTS: 80                             # Enable transport over HTTP. Comment out when not needed or allowed.
         ASPNETCORE_HTTPS_PORTS: 443                           # Enable transport over HTTPS. When HTTP is not enabled, HTTPS becomes mandatory.
         ELIAS_SERVICES: "query:8080, societal:8080"           # List all services in the format service:port. The query service is optional, as it is implied with default port 8080.
         ELIAS_DOMAIN: "${ELIAS_DOMAIN}"                       # Domain - provide the domain.tld for this ELIAS installation.
         SERVICE_2_ED: "${SERVICE_2_ED}"                       # SERVICE TO ELIAS DOMAIN - maps domain.tld to the appointed service, and requests certificate for it as well. So if service "web" is mapped, then domain.tld will point to the same "web" service. Use "-" for none.
         SERVICE_2_W3: "${SERVICE_2_W3}"                       # SERVICE TO www. ELIAS DOMAIN - maps 'www.domain.tld to the appointed service, and requests certificate for it as well. So if service "web" is mapped, then web.elias.domain.tld will point to the same "web" service. Use "-" for none.
         SERVICE_2_SD: "${SERVICE_2_SD}"                       # SERVICE TO sub DOMAIN. Can be "ON" or "OFF". When "ON", enables access to services omitting the ELIAS sub-domain name-space i.e. enables access to services via [service].domain.tld in addition to service.elias.domain.tld.
         TLSCERT_MAIL: "${TLSCERT_MAIL}"                       # Provide a valid email address to fetch a Let's Encrypt certificate. Use "-" when Let's Encrypt certificate should not be acquired. TLSCERT_MAIL is ignored when HTTPS is disabled.
