networks:
   elias_network:
      name: elias_network
      driver: bridge

volumes:
    elias_volume_system:
        external: true
    # elias_volume_mq_data:
    #     external: true
    # elias_volume_mq_log:
    #     external: true

services:
  elias_qs_mysql_db:
    image: mysql:latest
    container_name: elias_qs_mysql_db
    hostname: elias_qs_mysql_db
    restart: always
    environment:
      - MYSQL_TCP_PORT=3306
      - MYSQL_ROOT_PASSWORD=1234qQ1!
    ports:
      - 43306:3306
    volumes:
      - elias_volume_system:/var/lib/mysql
    networks:
      - elias_network

  elias_cache_redis:
    image: redis:latest
    container_name: elias_cache_redis
    hostname: elias_cache_redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - elias_network
  
  elias_message_queue_rabbit_mq:
    image: rabbitmq:management
    container_name: elias_message_queue_rabbit_mq
    hostname: elias_message_queue_rabbit_mq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    # volumes:
    #   - elias_volume_mq_data:/var/lib/rabbitmq
    #   - elias_volume_mq_log:/val/log/rabbitmq
    ports:
      - 5672:5672
    networks:
      - elias_network

  elias_gateway:
    image: miroslavbonchevbonchev/elias_gateway:latest
    container_name: elias_gateway
    hostname: elias_gateway
    restart: always
    build:
      context: .
      dockerfile: _system/ELIAS_Gateway/Dockerfile
    ports:
      - 51201:8080
      - 51202:8081
    depends_on:
      - elias_qs_mysql_db
      - elias_cache_redis
      - elias_message_queue_rabbit_mq
    networks:
      - elias_network

  elias_query_service:
    image: miroslavbonchevbonchev/elias_query_service:latest
    container_name: elias_query_service
    hostname: elias_query_service
    restart: always
    build:
      context: .
      dockerfile: Query_Service/Query_Service/Dockerfile
    depends_on:
      - elias_gateway
    networks:
      - elias_network

  elias_societal_service:
    image: miroslavbonchevbonchev/elias_societal_service:latest
    container_name: elias_societal_service
    hostname: elias_societal_service
    restart: always
    build:
      context: .
      dockerfile: Societal_Service/Societal_Service/Dockerfile
    depends_on:
      - elias_query_service
    networks:
      - elias_network
