version: '3.4'

networks:
   elias_network:

volumes:
    elias_volume:
        external: true

services:
  elias_query_service:
    container_name: elias_query_service
    image: ${DOCKER_REGISTRY-}elias_query_service
    restart: always
    build:
      context: .
      dockerfile: Query_Service/Query_Service/Dockerfile
    ports:
      - "51210:51210"
      - "51211:51211"
    networks:
      - elias_network
  
  elias_qs_mysql_db:
    container_name: elias_qs_mysql_db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_TCP_PORT=43306
      - MYSQL_ROOT_PASSWORD=1234qQ1!
    ports:
      - 43306:43306
    volumes:
      - elias_volume:/var/lib/mysql
    networks:
      - elias_network

  elias_cache_redis:
    image: redis:latest
    container_name: elias_cache_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - elias_network
