networks:
   elias_network:
      name: elias_network
      driver: bridge

volumes:
    elias_volume_system:
        external: true
    # elias_volume_mq_data:
    #     external: true
    # elias_volume_mq_log:
    #     external: true

services:
  elias_qs_mysql_db:
    image: mysql:8.4.0-oraclelinux8
    container_name: elias_qs_mysql_db
    hostname: elias_qs_mysql_db
    restart: always
    environment:
      - MYSQL_TCP_PORT=3306
      - MYSQL_ROOT_PASSWORD=1234qQ1!
    ports:
      - 43306:3306
    volumes:
      - elias_volume_system:/var/lib/mysql
    networks:
      - elias_network

  elias_cache_redis:
    image: redis:latest
    container_name: elias_cache_redis
    hostname: elias_cache_redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - elias_network

  elias_message_queue_rabbit_mq:
    image: rabbitmq:management
    container_name: elias_message_queue_rabbit_mq
    hostname: elias_message_queue_rabbit_mq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    # volumes:
    #   - elias_volume_mq_data:/var/lib/rabbitmq
    #   - elias_volume_mq_log:/val/log/rabbitmq
    ports:
      - 5672:5672
    networks:
      - elias_network



  # Define the installed services.
  elias_query_service:
    image: miroslavbonchevbonchev/elias_query_service:latest
    container_name: elias_query_service
    hostname: elias_query_service
    restart: always
    ports:
      - 8080
    depends_on:
      - elias_qs_mysql_db
      - elias_cache_redis
      - elias_message_queue_rabbit_mq
    networks:
      - elias_network
    environment:
      ASPNETCORE_HTTP_PORTS: 8080

  elias_societal_service:
    image: miroslavbonchevbonchev/elias_societal_service:latest
    container_name: elias_societal_service
    hostname: elias_societal_service
    restart: always
    ports:
      - 8080
    depends_on:
      - elias_query_service
    networks:
      - elias_network
    environment:
      ASPNETCORE_HTTP_PORTS: 8080

  elias_gateway:
    image: miroslavbonchevbonchev/elias_gateway:latest
    container_name: elias_gateway
    hostname: elias_gateway
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - elias_query_service
      - elias_societal_service
      #- elias_web_service
    networks:
      - elias_network
    environment:
      ASPNETCORE_HTTP_PORTS: 80
      ASPNETCORE_HTTPS_PORTS: 443
      ELIAS_SERVICES: "query:8080, societal:8080"           # Required - list all services in the format service:port. The query service is optional, as it is implied with default port 80.
      ELIAS_DOMAIN: "${ELIAS_DOMAIN}"                       # Required - provide the domain for this installation
      TLS_CERT_EMAIL: "${TLS_CERT_EMAIL}"                   # Required - use "none" when HTTPS cannot be implemented for some reason.
      # DOW3_TO_SERVICE: "societal"                           # Optional - defaults to none - map 'domain.tld (DO) and www.domain.tld (W3) to the appointed service, and requests certificate for them as well. So if web is mapped, then web.elias.domain.tld, web.domain.tld, domain.tld and www.domain.tld will point to the same web service. If omitted, the TLS certificate will not be requesting domain.tld and www.domain.tld will all point to the same service 'web', and certificates for all of these URI will be requested.
      # SERVICE_ALIAS: "ON"                                   # Optional - defaults to OFF  - When ON enables access to services omitting the ELIAS name-space sub-domain e.g. service.domain.tld in addition to service.elias.domain.tld. When OFF or omitted, access to services is only via service.elias.domain.tld.



# CALL: ELIAS_DOMAIN=el1.biz docker compose up -d