# Update
# - volume_to_restore - REQUIRED - replace with the volume to backup
# - host_backup_dir   - REQUIRED - replace with the directory of the backup
# - ZIP_ARCHIVE       - REQUIRED - replace with the filename of the backup
# The source archive must be: [host_backup_dir]/[ZIP_ARCHIVE].tar.gz, i.e.
# ASIS the source archive must be: ./host_backup_dir/elias_volume___system_gateway.tar.gz.
# Note that the backup is gz, as on some systems bz2 may not work properly.
#
# CALL
# docker compose -f restore-volume-system_gateway.yml run --rm go

volumes:
  elias_volume___system_gateway:
    external: true

services:
  go:
    image: alpine    
    environment:
      - ZIP_ARCHIVE=elias_volume___system_gateway.tar.gz
    volumes:
      - ./host_backup_dir:/container_backup_dir
      - elias_volume___system_gateway:/volume
    command: sh -c "rm -rf /volume/* /volume/..?* /volume/.[!.]* ; tar -C /volume/ -xvzf /container_backup_dir/$${ZIP_ARCHIVE}"
