version: "3.4"
# Update
# - volume_to_restore
# - host_backup_dir
# - ZIP_ARCHIVE

volumes:
  volume_to_restore:
    external: true

services:
  go:
    image: alpine    
    environment:
      - ZIP_ARCHIVE=name_of_the_zip_archive
    volumes:
      - ./host_backup_dir:/container_backup
      - volume_to_restore:/volume
    command: sh -c "rm -rf /volume/* /volume/..?* /volume/.[!.]* ; tar -C /volume/ -xvf /container_backup/$${ZIP_ARCHIVE}.tar.bz2"
