# Update
# - volume_to_restore - REQUIRED - replace with the volume to backup
# - host_backup_dir   - REQUIRED - replace with the directory of the backup
# - ZIP_ARCHIVE       - REQUIRED - replace with the filename of the backup
# The final archive must be on the path: host_backup_dir/ZIP_ARCHIVE.tar.gz
# Note that the backup is gz, as on some systems bz2 may not work properly.

volumes:
  volume_to_restore:
    external: true

services:
  go:
    image: alpine    
    environment:
      - ZIP_ARCHIVE=name_of_the_zip_archive
    volumes:
      - ./host_backup_dir:/container_backup
      - volume_to_restore:/volume
    command: sh -c "rm -rf /volume/* /volume/..?* /volume/.[!.]* ; tar -C /volume/ -xvf /container_backup/$${ZIP_ARCHIVE}.tar.bz2"
