# Update
# - volume_to_backup - REQUIRED - replace with the volume to backup
# - host_backup_dir  - OPTIONAL - replace with the directory for the backup
# - ZIP_ARCHIVE      - OPTIONAL - replace with the filename for the backup
# The final archive will be: [host_backup_dir]/[ZIP_ARCHIVE].tar.gz, i.e. 
# ASIS the final archive will be: ./host_backup_dir/elias_volume_system.tar.gz.
# Note that the backup is gz, as on some systems bz2 may not work properly.
#
# CALL
# docker compose -f direct_evs_volume_backup.yml run --rm go

volumes:
  elias_volume_system:
    external: true

services:
  go:
    image: alpine    
    tty: false
    environment:
      - ZIP_ARCHIVE=elias_volume_system
    volumes:
      - ./host_backup_dir:/container_backup_dir
      - elias_volume_system:/volume
    command: sh -c "tar -czvf /container_backup_dir/$${ZIP_ARCHIVE}.tar.gz -C /volume ./"
